version: '3.8'
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
 
  db:
    image: postgres:latest
    container_name: mydatabase
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - web
    command: ["nginx", "-g", "daemon off;"]